//
//  TestImage.swift
//
//  Created by Nixon Shih on 2020/9/9.
//

import Foundation

enum TestImage {
    static let base64Text = "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAAqADAAQAAAABAAAAAgAAAADtGLyqAAAAHGlET1QAAAACAAAAAAAAAAEAAAAoAAAAAQAAAAEAAABE5wHELAAAABBJREFUGBlimD59+o0bNwAAAAD//yQhvU8AAAANSURBVGO4cePG9OnTATxECJuNMYp3AAAAAElFTkSuQmCC"
    static var imageData: Data { Data(base64Encoded: TestImage.base64Text)! }    
}
